name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]
        laravel: [^9.0, ^10.0]
        include:
          - testbench: ^7.0
            laravel: ^9.0
          - testbench: ^8.0
            laravel: ^10.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: |
           composer require "illuminate/contracts=${{ matrix.laravel }}" --no-update
           composer require-dev "orchestra/testbench=${{ matrix.testbench }}" --no-update
           composer update --prefer-dist --no-interaction --no-progress

      - name: Execute unit tests
        run: vendor/bin/pest